#include "windows.h"
#include <stdio.h>

int main()
{
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR ntdll);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR wow64);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR wow64win);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR wow64log);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR wow64cpu);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR kernel32);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR KernelBase);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR atcuf32);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR oleaut32);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR msvcp_win);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR ucrtbase);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR combase);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR rpcrt4);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR user32);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR win32u);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR gdi32);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR gdi32full);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR advapi32);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR msvcrt);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR sechost);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR shell32);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR ole32);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR shlwapi);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR comdlg32);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR SHCore);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR imm32);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR imagehlp);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR ws2_32);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR version);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR opengl32);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR comctl32);
    WINBASEAPI HMODULE WINAPI LoadLibraryA(LPCSTR wsock32);

    for (int i = 0;; i++)
    {
        printf("Code Running:");
    }
}
