# Source : https://stackoverflow.com/questions/252417/how-can-i-use-a-dll-file-from-python

from ctypes import *

# Load DLLs into memory.

#WinDLL('ntdll.dll')
WinDLL(r'C:\Windows\System32\ntdll.dll')
WinDLL(r'C:\Windows\SysWOW64\ntdll.dll')
WinDLL(r'C:\Windows\System32\wow64.dll')
WinDLL(r'C:\Windows\System32\wow64win.dll')
WinDLL(r'C:\Windows\System32\wow64log.dll')
WinDLL(r'C:\Windows\System32\wow64cpu.dll')
WinDLL(r'C:\Windows\SysWOW64\kernel32.dll')
WinDLL(r'C:\Windows\SysWOW64\KernelBase.dll')
WinDLL(r'C:\Program Files\Bitdefender\Bitdefender Security\atcuf\dlls_265827483885032704\atcuf32.dll')
WinDLL(r'C:\Windows\SysWOW64\oleaut32.dll')
WinDLL(r'C:\Windows\SysWOW64\msvcp_win.dll')
WinDLL(r'C:\Windows\SysWOW64\ucrtbase.dll')
WinDLL(r'C:\Windows\SysWOW64\combase.dll')
WinDLL(r'C:\Windows\SysWOW64\rpcrt4.dll')
WinDLL(r'C:\Windows\SysWOW64\user32.dll')
WinDLL(r'C:\Windows\SysWOW64\win32u.dll')
WinDLL(r'C:\Windows\SysWOW64\gdi32.dll')
WinDLL(r'C:\Windows\SysWOW64\gdi32full.dll')
WinDLL(r'C:\Windows\SysWOW64\advapi32.dll')
WinDLL(r'C:\Windows\SysWOW64\msvcrt.dll')
WinDLL(r'C:\Windows\SysWOW64\sechost.dll')
WinDLL(r'C:\Windows\SysWOW64\shell32.dll')
WinDLL(r'C:\Windows\SysWOW64\ole32.dll')
WinDLL(r'C:\Windows\SysWOW64\shlwapi.dll')
WinDLL(r'C:\Windows\SysWOW64\comdlg32.dll')
WinDLL(r'C:\Windows\SysWOW64\SHCore.dll')
WinDLL(r'C:\Windows\SysWOW64\imm32.dll')
WinDLL(r'C:\Windows\SysWOW64\imagehlp.dll')
WinDLL(r'C:\Windows\SysWOW64\ws2_32.dll')
WinDLL(r'C:\Program Files\Cheat Engine 7.4\version.dll')
WinDLL(r'C:\Windows\SysWOW64\version.dll')
WinDLL(r'C:\Program Files\Cheat Engine 7.4\opengl32.dll')
WinDLL(r'C:\Windows\SysWOW64\opengl32.dll')
WinDLL(r'C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_a8625c1886757984\comctl32.dll')
WinDLL(r'C:\Program Files\Cheat Engine 7.4\lua53-32.dll')
WinDLL(r'C:\Program Files\Cheat Engine 7.4\wsock32.dll')
WinDLL(r'C:\Windows\SysWOW64\wsock32.dll')
WinDLL(r'C:\Program Files\Cheat Engine 7.4\wininet.dll')
WinDLL(r'C:\Program Files\Cheat Engine 7.4\GLU32.dll')
WinDLL(r'C:\Windows\SysWOW64\glu32.dll')
WinDLL(r'C:\Windows\SysWOW64\uxtheme.dll')
WinDLL(r'C:\Program Files\Cheat Engine 7.4\msimg32.dll')
WinDLL(r'C:\Program Files\Cheat Engine 7.4\win32\msimg32.dll')
WinDLL(r'C:\Windows\SysWOW64\msimg32.dll')
WinDLL(r'C:\Windows\SysWOW64\rpcss.dll')
WinDLL(r'C:\Windows\SysWOW64\kernel.appcore.dll')
WinDLL(r'C:\Windows\SysWOW64\bcryptprimitives.dll')
WinDLL(r'C:\Program Files\Cheat Engine 7.4\tcc32-32.dll')
WinDLL(r'C:\Windows\SysWOW64\clbcatq.dll')
WinDLL(r'C:\Windows\SysWOW64\ExplorerFrame.dll')
WinDLL(r'C:\Windows\SysWOW64\shfolder.dll')
WinDLL(r'C:\Windows\SysWOW64\windows.storage.dll')
WinDLL(r'C:\Program Files\Cheat Engine 7.4\Wldp.dll')
WinDLL(r'C:\Program Files\Cheat Engine 7.4\win32\Wldp.dll')
WinDLL(r'C:\Windows\SysWOW64\wldp.dll')
WinDLL(r'C:\Program Files\Cheat Engine 7.4\profapi.dll')
WinDLL(r'C:\Program Files\Cheat Engine 7.4\win32\profapi.dll')
WinDLL(r'C:\Windows\SysWOW64\profapi.dll')
WinDLL(r'C:\Windows\SysWOW64\psapi.dll')
WinDLL(r'C:\Program Files\Cheat Engine 7.4\PROPSYS.dll')
WinDLL(r'C:\Program Files\Cheat Engine 7.4\win32\PROPSYS.dll')
WinDLL(r'C:\Windows\SysWOW64\propsys.dll')
WinDLL(r'C:\Windows\SysWOW64\msctf.dll')
WinDLL(r'C:\Windows\SysWOW64\ntdll.dll')

while True:
    print("Code Running")
